### ISSUE TITLE
Import Calendar : 8 -> 21

### ISSUE THREAD

**Issue by jordre3** [CSBSJU-CS330-F19/SocialHour#4]
As a user, I want to be able to import my existing Android Calendar so I do not have re-enter the information in another app.

Done: Ability to read and write from/to calendar.

Tasks: 
- Research Google Calendar API (1 hr/Completed)
- Use gradle to incorporate API into project (1-2 hr/Completed)
- Use google's java quickstart code to set up (1-2 hr/Completed)
- Test ability to read from from calendar (1-2 hr/In Progress)

**Comment by kathryncdempsey** [comment]
Use Google Calendar API
