### ISSUE TITLE
Create an Account : 21

### ISSUE THREAD

**Issue by jordre3** [CSBSJU-CS330-F19/SocialHour#6]
As a user, I want to create an account so that I can interact with the app and join groups with other users. 

We should check to make sure that their email is not already a username in our database.

Done: Database is set up to contain user information (email, password, name). After completing the create an account form, your information is stored in the database. User Interface for creating an account is complete.

Tasks: Set up the database, Create UI, Test for all cases.

**Comment by jtholen001** [comment]
This would include creating and setting up the database
